### PR TITLE
Drop python wrapper

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by LightArrowsEXE** [comment]
Why not point users to the wrappers in vsscale instead of unceremoniously dropping the wrapper in here?

**Comment by ghost** [comment]
Personally don't see it as necessary, the wrapper was never really used to begin with. If arch sees fit to mention vskernels instead then he can do so.

**Comment by arch1t3cht** [comment]
I'm happy to yeet the wrapper, personally. It uses some bad settings (>Spline36) and half of its core features (comverting to float and back) are part of the plugin itself now. The one helpful feature are the python enums for the `opt` and `border_handling` options, but having those as just numbers is fairly commonplace for VS filters.

**Comment by LightArrowsEXE** [comment]
If you really wanted, you could probably put those in vsscale too.

**Pull request merged**
